### ISSUE TITLE
Segfault in 2022.03.16

### ISSUE THREAD

**Issue by asdil12** [daid/SeriousProton#213]
When compiling and starting the recent version of EmptyEpsilon, the following segfault happens, when pressing *start server* or *start client* in the main menu.

```
Thread 1 "EmptyEpsilon" received signal SIGSEGV, Segmentation fault.                                    
0x00000000007f9b30 in sp::io::network::Address::getLocalAddress() ()

(gdb) bt
#0  0x00000000007f9b30 in sp::io::network::Address::getLocalAddress() ()
#1  0x00000000004fb2f2 in ServerSetupScreen::ServerSetupScreen() ()
#2  0x00000000004e9ade in MainMenu::MainMenu()::{lambda()#2}::operator()() const ()
#3  0x00000000004f3978 in void std::__invoke_impl<void, MainMenu::MainMenu()::{lambda()#2}&>(std::__invoke_other, MainMenu::MainMenu()::{lambda()#2}&) ()
#4  0x00000000004f2f91 in std::enable_if<is_invocable_r_v<void, MainMenu::MainMenu()::{lambda()#2}&>, void>::type std::__invoke_r<void, MainMenu::MainMenu()::{lambda()#2}&>(MainMenu::MainMenu()::{lambda()#2}&)
    ()
#5  0x00000000004f27b3 in std::_Function_handler<void (), MainMenu::MainMenu()::{lambda()#2}>::_M_invoke(std::_Any_data const&) ()
#6  0x0000000000418954 in std::function<void ()>::operator()() const ()
#7  0x00000000006573a7 in GuiButton::onMouseUp(glm::vec<2, float, (glm::qualifier)0>, long) ()
#8  0x000000000064c85d in GuiCanvas::onPointerUp(glm::vec<2, float, (glm::qualifier)0>, long) ()
#9  0x00000000007b2e66 in RenderLayer::onPointerUp(glm::vec<2, float, (glm::qualifier)0>, long) ()
#10 0x00000000007b2eca in RenderLayer::onPointerUp(glm::vec<2, float, (glm::qualifier)0>, long) ()
#11 0x00000000007b0844 in PostProcessor::onPointerUp(glm::vec<2, float, (glm::qualifier)0>, long) ()
#12 0x00000000007b0844 in PostProcessor::onPointerUp(glm::vec<2, float, (glm::qualifier)0>, long) ()
#13 0x00000000007eccdb in Window::handleEvent(SDL_Event const&) ()
#14 0x000000000073b675 in Engine::handleEvent(SDL_Event&) ()
#15 0x000000000073adc4 in Engine::runMainLoop() ()
#16 0x000000000040e890 in main ()
(gdb) 
```

The error seems to be happening in this line in `src/io/network/address.cpp`:
```cc
if (addr->ifa_addr->sa_family == AF_INET)
```

There is a check in the loop if `addr` is `null` but in this case `addr` is fine but `addr->ifa_addr` is `null`.

I'm not sure if there is a deeper issue, but this patch fixes it:
```diff
--- SeriousProton-EE-2022.03.16/src/io/network/address.cpp      2022-03-15 23:05:53.000000000 +0100
+++ /tmp/address.cpp    2022-09-15 12:23:30.305529074 +0200
@@ -130,6 +130,10 @@
             {
                 continue;
             }
+            //printf("addr->ifa_addr is %p\n", (void *)addr->ifa_addr);
+            if (addr->ifa_addr == nullptr) {
+                continue;
+            }
             if (addr->ifa_addr->sa_family == AF_INET)
             {
                 ::getnameinfo(addr->ifa_addr, sizeof(struct sockaddr_in), buffer, sizeof(buffer), nullptr, 0, NI_NUMERICHOST);
```

**Comment by asdil12** [comment]
Seems that this is already fixed via https://github.com/daid/SeriousProton/issues/209
